name: gradvis_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.0
  go_router: ^17.1.0
  google_fonts: ^8.0.1
  json_annotation: ^4.10.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.12.0
  build_runner: ^2.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/music/theme.mp3
  fonts:
    - family: Fredoka One
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf
